export const ADD_USER = 'ADD_USER'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const CLEAR_USER = 'CLEAR_USER'
export const CLEAR_BUCKET_USER = 'CLEAR_BUCKET_USER'


export const ADD_PRODUCT_INITIAL ='ADD_PRODUCT_INITIAL'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const OK_SUCCESS = 'OK_SUCCESS'

export const ADD_SUB_PRODUCT = 'ADD_SUB_PRODUCT'
export const ADD_SUB_PRODUCT_FAIL = 'ADD_SUB_PRODUCT_FAIL'
export const ADD_SUB_PRODUCT_SUCCESS = 'ADD_SUB_PRODUCT_SUCCESS'
export const OK_SUB_SUCCESS = 'OK_SUB_SUCCESS'

export const ADD_PRODUCT_INFO = 'ADD_PRODUCT_INFO'
export const ADD_PRODUCT_INFO_FAIL = 'ADD_PRODUCT_INFO_FAIL'
export const ADD_PRODUCT_INFO_SUCCESS = 'ADD_PRODUCT_INFO_SUCCESS'
export const OK_INFO_SUCCESS = 'OK_INFO_SUCCESS'

export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST'
export const GET_PRODUCTS_LIST_SUCCESS = 'GET_PRODUCTS_LIST_SUCCESS'

export const GET_PRODUCT_INFO = 'GET_PRODUCT_INFO'
export const GET_PRODUCT_INFO_FAIL = 'GET_PRODUCT_INFO_FAIL'
export const GET_PRODUCT_INFO_SUCCESS = 'GET_PRODUCT_INFO_SUCCESS'

export const ADD_LIKE_PRODUCT = 'ADD_LIKE_PRODUCT'
export const ADD_LIKE_PRODUCT_FAIL = 'ADD_LIKE_PRODUCT_FAIL'
export const ADD_LIKE_PRODUCT_SUCCESS = 'ADD_LIKE_PRODUCT_SUCCESS'

export const GET_PRODUCTS_LIKE_INITIAL = 'GET_PRODUCTS_LIKE_INITIAL'
export const GET_PRODUCTS_LIKE_FAIL = 'GET_PRODUCTS_LIKE_FAIL'
export const GET_PRODUCTS_LIKE_SUCCESS = 'GET_PRODUCTS_LIKE_SUCCESS'

export const ADD_BUY_PRODUCT = 'ADD_BUY_PRODUCT'

export const GET_PRODUCTS_BUY_INITIAL = 'GET_PRODUCTS_BUY_INITIAL'
export const GET_PRODUCTS_BUY_FAIL = 'GET_PRODUCTS_BUY_FAIL'
export const GET_PRODUCTS_BUY_SUCCESS = 'GET_PRODUCTS_BUY_SUCCESS'

export const ADD_PRICE_PRODUCT = 'ADD_PRICE_PRODUCT'
export const MINUS_PRICE_PRODUCT = 'MINUS_PRICE_PRODUCT'
export const CLEAR_BUCKET = 'CLEAR_BUCKET'

export const GET_NEWS = 'GET_NEWS'
export const GET_NEWS_FAIL = 'GET_NEWS_FAIL'
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS'

export const ADD_NEWS = 'ADD_NEWS'
export const ADD_NEWS_FAIL = 'ADD_NEWS_FAIL'
export const ADD_NEWS_SUCCESS = 'ADD_NEWS_SUCCESS'
export const OK_NEWS_SUCCESS = 'OK_NEWS_SUCCESS'

export const DELETE_NEWS = 'DELETE_NEWS'
export const DELETE_NEWS_FAIL = 'DELETE_NEWS_FAIL'
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS'
export const OK_DELETE_NEWS_SUCCESS = 'OK_DELETE_NEWS_SUCCESS'

export const GET_FULL_DATA = 'GET_FULL_DATA'
export const GET_FULL_DATA_FAIL = 'GET_FULL_DATA_FAIL'
export const GET_FULL_DATA_SUCCESS = 'GET_FULL_DATA_SUCCESS'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL'
export const UPDATE_PRDUCT_SUCCESS = 'UPDATE_PRDUCT_SUCCESS'
export const OK_UPDATE_SUCCESS = 'OK_UPDATE_SUCCESS'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'
export const DELETE_PRDUCT_SUCCESS = 'DELETE_PRDUCT_SUCCESS'
export const OK_DELETE_SUCCESS = 'OK_DELETE_SUCCESS'

export const GET_COUNT_SELL_PRODUCT = 'GET_COUNT_SELL_PRODUCT'
export const GET_COUNT_SELL_PRODUCT_FAIL = 'GET_COUNT_SELL_PRODUCT_FAIL'
export const GET_COUNT_SELL_PRODUCT_SUCCESS = 'GET_COUNT_SELL_PRODUCT_SUCCESS'